services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  ingestion:
    build:
      context: .
      dockerfile: deployments/docker/ingestion.Dockerfile
    image: bmstu-practice-ingestion:local
    container_name: ingestion-service
    depends_on:
      - kafka
    environment:
      HTTP_ADDR: ":8080"
      PUBLISHER_BACKEND: "kafka"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TELEMETRY_TOPIC: "telemetry.raw"
    ports:
      - "8080:8080"

  processing:
    build:
      context: .
      dockerfile: deployments/docker/processing.Dockerfile
    image: bmstu-practice-processing:local
    container_name: processing-service
    depends_on:
      - kafka
    env_file:
      - configs/processing.env.example
    ports:
      - "8081:8081"
